# Generated by Django 4.2.7 on 2023-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogyy', '0002_post_category_post_like_by_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
